### ISSUE TITLE
Unintuitive file location?

### ISSUE THREAD

**Issue by Deniz1433** [PrincessAkira/Discord-Fixer#4]
Discord updates overwrite everything in the folder AppData\Local\Discord\app-1.0.9026, including this programs executable, so after updates like this I'm forced to download it again and put it there again.
Althought it could be about Vencord updating too, not sure.

**Comment by Aetopia** [comment]
I made a fork and addressed that issue in it. 
https://github.com/PrincessAkira/Discord-Fixer/pull/5

**Comment by Aetopia** [comment]
Check the latest release on this repo which addresses this issue.

**Comment by PrincessAkira** [comment]
Should be fixed in Release 2.0
