### ISSUE TITLE
Virustotal flags

### ISSUE THREAD

**Issue by DefinedYuki** [PrincessAkira/Discord-Fixer#6]
While testing Discord-Fixer and to see if the issue #3 will occur on my end (Which did not happen, the software works without any issues) I noticed that "Windows Defender Smartscreen" is flagging the program. Upon also scanning the file I noticed that it gets 11 false flags where one is from Google.

[Virustotal Scan Result](https://www.virustotal.com/gui/file/36ce336a19f9a7081d58ed27ffbcfbc6a02254df0b63b06bd0efc6c67d897f67/detection)

I created this issue as a notifier about the false flags and wanted to ask if this issue could be relevant to fix, as Google is also flagging it or can the issue be closed without any further things needing to be done? 

Should this issue be not relevant, then I'm sorry for wasting time 🙏

**Comment by PrincessAkira** [comment]
Accessing threads. 
False flags, nothing i can do
