### ISSUE TITLE
Latest release does not lauch Discord on double-click

### ISSUE THREAD

**Issue by Scarlaid** [PrincessAkira/Discord-Fixer#8]
Recently, the latest update seem to be not launching Discord on start
Going back to version 1.2 launchs fine

![NVIDIA_Share_NGGYYce7OU](https://github.com/PrincessAkira/Discord-Fixer/assets/90851437/5db46019-e965-4fca-afaf-2fcd64cc6c62)

**Comment by m2rk1312** [comment]
Having the same issue

**Comment by PrincessAkira** [comment]
Again. 
Wrong folder. Read the readme :D

**Comment by PrincessAkira** [comment]
TLDR:
Closing. If further issues happen with the same thing, just reopen this and ill look into it
